### ISSUE TITLE
Cheers !!!

### ISSUE THREAD

**Issue by Duan-JM** [sarrost/dotfiles#1]
Just want to show my thanks for these wonderful arts ~~ Thanks for sharing~

**Comment by sarrost** [comment]
> Just want to show my thanks for these wonderful arts ~~ Thanks for sharing~

Lol thanks :3

**Comment by sarrost** [comment]
I'm still new to github, I didn't mean to close your "issue/comment" lol.

**Comment by Duan-JM** [comment]
It's okay to close it :3 ~ Just want to express my thanks for this~

**Comment by sarrost** [comment]
Cool beans :^>
